- src/text.c
For custom number of connections, if the value given is less than 1, the program halts with Segmentation Fault. Added a check in `src/text.c` which checks `conf->num_connections` to be greater than 1 after the parameters have been passed, otherwise it executes `print_help()` and terminates.
> Fixed num_connections error when invalid values are given

- configure.ac
Fixes these errors when running ./autogen.sh on Linux
Copying file config.rpath
Copying file /codeset.m4
cp: cannot create regular file ‘/codeset.m4’: Permission denied
Copying file /fcntl-o.m4
cp: cannot create regular file ‘/fcntl-o.m4’: Permission denied
Copying file /gettext.m4
cp: cannot create regular file ‘/gettext.m4’: Permission denied
Copying file /glibc2.m4
(... lots more of these)
> Add missing m4 path

- src/ssl.c
This fixes SSL WANT_READ error wihch causes `Connection gone` error sometimes.
fixes #22
> Set SSL auto-retry mode

- configure.ac
AC_FUNC_MALLOC & AC_FUNC_REALLOC cause link errors when cross-compiling.
It seems the preferred solution is to just remove them, and optionally adding
them to the AC_CHECK_FUNCS section.
eg.
https://github.com/LLNL/ior/issues/4
http://rickfoosusa.blogspot.com.au/2011/11/howto-fix-undefined-reference-to.html
> Fix rpl_malloc not found when cross-compiling

- configure.ac
Fix a FTBFS when using OpenSSL 1.1.0. For details, see 'HISTORY' here[1].
This fix will close the bug #829452 in Debian[2].
@sdt, can you check this change and commit? Thanks!
Eriberto
[1] https://www.openssl.org/docs/manmaster/ssl/SSL_library_init.html
[2] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829452
> Fix a build fail when using OpenSSL 1.1.0

- src/conn.c
- src/http.c
- src/http.h
This is a possible solution for bug #33.
The commit extracts file sizes from the `Content-Range` header as well. If it is present and the file size given in the header differs from the file size given in the `Content-Length` header, then the larger of the two numbers is used as the file size.
If you'd prefer to in this case switch off partial downloading entirely, then this commit is still a good basis do to that. All that'd need to be changed is that in line 381, `supported` must be set to `0` instead of `1´.
> Extract file sizes from the Content-Range header

- po/ja.po
Added:
- `--insecure` and also `-k`
- the link to GitHub Issue page
- connection error messages in SSL and the normal
- the guidance to CREDITS
Fixed:
- the expressions of time
> l10n/ja: update translation

- configure.ac
This one fixes configure flag to enable building with TLS support when it's forcefully requested. There are two options here:
- use `[]` as per [example in the doc](https://www.gnu.org/software/autoconf/manual/autoconf-2.60/html_node/External-Software.html)
- use `[with_openssl=${withval}]`, so the value is passed correctly later on
I decided to go with the first option since I find it shorter and more elegant. It should work for both `--with-openssl` and `--with-openssl=yes`.
> Fix '--with-openssl' flag

- src/axel.c
fix a use-after-free that might actually be linked to #50 . Although what I saw here happens only when killing the download and not before.
==============
When stopping the download, axel->conn should not
be free'd before having invoked save_state() as it
will be accessed once again to retrieve the current
state.
This use-after-free is easy reproducible on linux when
running axel with at least 10 connections. Probably, due to
some optimization, a smaller number of connections does not
trigger an immediate deallocation of the used heap and
therefore does not exhibit the bug.
Fix this issue by moving the free(axel->conn) instruction
to the end of the cleanup function.
> fix use-after-free of axel->conn member

- src/axel.c
- src/conn.c
axel->size is of type long long, therefore LLONG_MAX
should be used as max/err value instead of INT_MAX.
> use proper max value for size

- src/axel.c
- src/conn.c
Fixes bug reported at: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=449513
=========================================
When switching from HTTP to FTP the entire conn
object has to be re-init'd.
Therefore conn_info() has to invoke conn_set()
and then return, so to give conn_init() a chance
to run again.
At this point the connection is ready to retrieve
the file size.
> fix redirection from HTTP to FTP

- src/axel.c
- src/conn.c
Ensure that snprintf is provided with the right size
parameters in order to accommodate the length of its
arguments.
This issue was found by compiling axel with gcc-7.1.0.
> fix snprintf length argument

- src/text.c
This is another bunch of fixes I came up with after checking more code.
Unfortunately it seems that there are some more objects (mostly within the conn[] data structure) that are accessed by the main thread as well as the secondary ones without locking/coordination. The code is pretty simple so it is difficult to trigger a real race condition, but the likelihood increases drastically when increasing the number of connections. Most of these race conditions are not fixed in this pull request.
> Various fixes2

- src/axel.c
- src/axel.h
- src/search.c
- src/text.c
Fixes issue #61 
==================================
nanosleep is interrupted when a signal is delivered to
the sleeping thread. In that case axel will abort
whatever it was doing.
> convert usleep to nanosleep

- man/axel.1
- man/axel.txt
- src/axel.h
- src/conf.c
- src/conf.h
- src/conn.c
- src/text.c
I find annoying that sometimes portage (package manager on Gentoo) fails to download a package because the number of redirects allowed by axel is too small.
In those cases I have to fallback to wget and download the package manually.
With these small patches axel's behaviour becomes equal to wget:
1. set max redirects to 20 by default
2. allow max redirects to be tuned from command line
> enhance max number of redirections

- .travis.yml
add basic support to build axel on linux (gcc & clang) and on osx.
I can't configure travis-ci myself because I am not owner/collaborator on the main repo, therefore it does not appear in my travis-ci panel.
> add basic travis-ci support

- src/http.c
- src/http.h
Improves PR #43 .
I wanted to add a Reported-by, but I don't know the name and the email of the reporter.
==============================
When the port being used during a HTTP connection is
different from the service default (80 or 443), the Host:
HTTP header should also contain the actual port being used,
as specified by RFC2616 section 14.23.
> Add port to Host HTTP header when different from service default

- doc/axelrc.example
I hadn't realized that axel ships a axelrc.example file too.
> Add description for max_redirect to axelrc.example

- src/axel.c
- src/axel.h
- src/text.c
Avoid crash in alternate output, when axel can't get the terminal window spec.
> Fix crash in alternate output

- src/http.c
- src/http.h
This is the patch taken from https://lists.alioth.debian.org/pipermail/axel-devel/2011-February/000198.html reformatted and cleaned up a bit. Unfortunately my test proxy (privoxy) does not support HTTP auth and therefore I couldn't this this.
Solves: #84 
===========================
A proxy server might require HTTP authentication too.
Ass support for such feature via HTTP header.
Signed-off-by: Tirtha Chatterjee <tirtha.p.chatterjee@gmail.com>
> Implement HTTP authentication support

- .travis.yml
This way travis-ci will fail if a new warning is
detected and give a chance to the developers to notice
that.
> Let travis-ci compile with -Werror

- doc/axelrc.example
- man/axel.1
- man/axel.txt
- src/conf.c
- src/conf.h
- src/conn.c
- src/tcp.c
- src/tcp.h
- src/text.c
Solves #40 
===========================
Like wget, enable the user to choose the IP protocol to use.
This can now be done using the long opt "use-protocol=[ipv4,ipv6]"
in the axelrc file or by using the related command line options
--ipv4/-4 and --ipv6/-6.
> Allow user to choose between IPv4 and IPv6

- doc/axelrc.example
- man/axel.1
- man/axel.txt
- src/axel.c
- src/conf.c
- src/conf.h
- src/text.c
Like wget, when the --no-clobber option is specified, skip
download if a file with the same name already exists in the
current directory.
Closes: https://github.com/axel-download-accelerator/axel/issues/37
This PR supersedes PR #94 .
> Add --no-clobber option

- configure.ac
- src/axel.h
- src/conn.c
- src/ssl.c
- src/ssl.h
- src/tcp.c
- src/tcp.h
- src/text.c
As a first step towards making the code libssl generic,
rename all the constants (including strings in configure.ac)
from OpenSSL to SSL only.
> Rename constants from OpenSSL to SSL

- src/axel.c
In my opinion this is worth a 2.14.1 release.
===========================================
Under certain condition, it is possible to stall the
download because the connection lock is not properly
released within the connection status check loop.
Make sure that the connection lock is released before
moving to the next entry under every condition.
> Avoid stall due to missing unlock

- .travis.yml
Setting the `PKG_CONFIG_PATH` should let configure find openssl.
> Travis: fix OS X SSL build

- README.md
Add `autoconf-archive` in the building dependency list.
Signed-off-by: Kun Ma <kun.ma@citrix.com>
> add 'autoconf-archive' in readme.md building instruction

- src/text.c
The issue is evident when fetching over HTTP/FTP (HTTPS much less so):
$ axel http://speed.hetzner.de/1GB.bin
Initializing download: http://speed.hetzner.de/1GB.bin
File size: 1048576000 bytes
Opening output file 1GB.bin
Starting download
[  0%]  .......... .......... .......... .......... ..........  [
290.7KB/s]
[  0%]  .......... .......... .......... .......... ..........  [
512.6KB/s]
[  0%]  .......... .......... .......... ......... ........  [
727.7KB/s]
[  0%]  ........ ....... .......... ..................  [ 825.2KB/s]
[  0%]  ................. ....... ........ .......  [ 958.2KB/s]
[  0%]  ....... ............... ......... ..........................
......... ......... .......  [1176.6KB/s]
[  0%]  ......... ....... .......................  [1303.1KB/s]
[  0%]  ........ …
> Fix progress indicator misalignment in some cases

- src/tcp.c
ssl_disconnect() does not close sockets, leading to file descriptor leaks.
Program abortions were also observed if users called axel with a lot of
connections to download a big file.
Explicitly call close(2) on SSL connections too.
Signed-off-by: Park Ju Hyung <qkrwngud825@gmail.com>
> tcp: explicitly close sockets on SSL connections too

- README.md
Initially this was going to be a typo fix, but as I read more I noticed several miswordings which may be confusing to non-native English speakers, so I have changed them.
> Improve English in README.md

- src/text.c
Small changes to make sure User-Agent and custom headers all get included in the request. Also a safety check to make sure Axel doesn't write more custom headers to memory than it has space for.
I got rid of the cur_head variable because it didn't seem to be doing anything except for introducing a bug.
fixes #265, fixes #266
> Fix headers bugs

- src/http.c
Fixes #429.
This not mostly ideal (RFC 6266 prefers `filename*` if present) yet may be considered good enough if we don't want to introdue UTF-8 decoding here.
> http: Fix filename parsing from content-disposition
